---
title: "Adding glottocode to bibtex"
output: html_document
---

Basic settings
```{r}
library(tidyverse)
options(stringsAsFactors = F)
```

read original bib file and language file
```{r}
# read bib file
bib <- readLines("old_data/sources.bib")
# remove previous WALS code annotations
bib[str_detect(bib,"Wals_code")] <- ""
# read language file
langs <- read.csv("old_data/GSSG_ListOfLanguages.csv", sep = ";")
str(langs)
```

add wals codes or glottocodes
```{r}
for(i in 1:length(langs$source)){
  if(str_detect(bib[str_detect(bib,langs$source[i])], "Wals_code") == FALSE){
  bib[str_detect(bib,langs$source[i])] <- paste(bib[str_detect(bib,langs$source[i])],
                                                " Wals_code = {", langs$wals_code[i], "},",
                                                sep = "")
  }
  else{
   bib[str_detect(bib,langs$source[i])] <- str_replace(bib[str_detect(bib,langs$source[i])], 
                                                       "\\},",
                                                       paste("; ",langs$wals_code[i],"},",
                                                             sep = ""))
  }
}
```

change all bib refs to lower case to make them work in clld
```{r}
bib[str_detect(bib,"Wals_code")] <- gsub("(\\{.)","\\L\\1", bib[str_detect(bib,"Wals_code")],perl=TRUE)
```


Extract output
```{r}
writeLines(bib, "sources.bib")
```

Also change everything to lower case in the master table
```{r}
langs$source <- gsub("(^.)","\\L\\1", langs$source, perl = TRUE)
```

export the file 
```{r}
write.csv2(langs, "GSSG_ListOfLanguages.csv", sep = ";")
```

```{r}

```

